services:
  back-end:
    image: softy-pinko:task5-back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-end

  front-end:
    image: softy-pinko:task5-front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    depends_on:
      - back-end

  proxy:
    image: softy-pinko:task5-proxy
    ports:
      - "80:80"
    build:
      context: ./proxy
      dockerfile: Dockerfile
